name: build_image_coment_suru_kun
on: [push]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set git commit hash short
        id: git-commit-hash-short
        run: echo "::set-output name=HASH_SHORT::$(git rev-parse --short HEAD)"

      - name: set pull request number
        id: pull-request-number
        run: echo "::set-output name=PR_NUMBER::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)

      - name: send comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.pull-request-number.outputs.PR_NUMBER }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Build image: `pr-${{ steps.pull-request-number.outputs.PR_NUMBER }}.${{ steps.git-commit-hash-short.outputs.HASH_SHORT }}`'
            })
