name: create release pr
on:
  push:
    branches:
      - develop

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: create release pr
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
          GIT_PR_RELEASE_TEMPLATE: ./.github/git-pr-release-template.erb
        run: |
          gem install -N git-pr-release -v "2.1.1"
          git-pr-release --no-fetch
